project_id = "pegkzuxbgswqouieordl"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.facebook-webhook]
verify_jwt = false

[functions.facebook-oauth-callback]
verify_jwt = false

[functions.instagram-webhook]
verify_jwt = false